### ISSUE TITLE
[[ -k /tmp ]] / test -k /tmp not supported (ble.sh)

### ISSUE THREAD

**Issue by akinomyoga** [oilshell/oil#649] opened 2020-03-09 05:34 UTC
ble.sh uses this. It tests the sticky bit (See the manual of Bash). I think this is relatively easy to support.

```console
$ bin/osh -c '[[ -k /tmp ]]'
  [[ -k /tmp ]]
        ^~~~
[ -c flag ]:1: Expected ]]
$ bin/osh -c 'test -k /tmp'
  test -k /tmp
       ^~
[ -c flag ]:1: (test) Expected unary operator, got '-k' (2 args)
$
```

**Comment by andychu** [comment] 2020-03-09 06:51
Actually this is a dupe of #537

**Closed** 2020-03-09 06:51 UTC
Labels: good first issue, help wanted, osh-language
