### ISSUE TITLE
Exclamation mark waits for background processes to finish

### ISSUE THREAD

**Issue by lhoursquentin** [oilshell/oil#416] opened 2019-07-09 07:11 UTC
```bash
/bin/sleep 10 &

echo begin
! true
echo end
```
Waits 10 seconds on the `! true` line, seems like `!` is the trigger. Maybe it's a feature? Seems a bit odd.

**Comment by andychu** [comment] 2019-07-09 08:05
Confirmed, another nice find... I think this has to do with the fact that `! true` is technically a pipeline (according to POSIX grammar), and pipelines are waited for differently than regular processes.

**Comment by andychu** [comment] 2019-07-09 17:19
Yeah great catch, this happened when I changed OSH to use `shopt -s lastpipe` semantics like zsh.

As mentioned, `! true` is a pipeline with one element.  Because `!` applies to the entire pipeline status.

So we were waiting for one process instead of zero, so we were picking up the background process.

Fixed now, thanks!

**Comment by andychu** [comment] 2019-07-17 19:20
Released with 0.7.pre1: https://www.oilshell.org/release/0.7.pre1/

**Closed by andychu** 2019-07-17 19:20 UTC
Labels: high-priority, pending-release
