### ISSUE TITLE
pipelines not expanded in aliases

### ISSUE THREAD

**Issue by RobSykes** [oilshell/oil#226] opened 2019-02-08 13:40 UTC
osh$ alias t1='ls|wc'
osh$ t1
INSTALL.txt  LICENSE.txt  Makefile  Python-2.7.13  _bin  _build  _devbuild  _release  _tmp  build  configure  install  native

(apologies for typo in bug title)

**Comment by andychu** [comment] 2019-02-08 18:15
Thank you, I reproduced this!

I'm not sure what the fix is yet, since alias is quirky to implement, but I agree it's a bug.

**Comment by andychu** [comment] 2019-02-09 06:50
Thanks for the report!  I fixed this and it will be released with 0.6.pre14, hopefully in a few days.

**Comment by andychu** [comment] 2019-02-19 02:12
Released, thanks for the report: http://www.oilshell.org/blog/2019/02/18.html

**Closed by andychu** 2019-02-19 02:12 UTC
Labels: pending-release
