### ISSUE TITLE
Fatal error when using an undefined array's value in arithmetic expressions

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#300] opened 2019-05-07 07:32 UTC
```bash
$ (( arr[0] ))
  (( arr[0] ))
     ^~~
'/home/user/.config/oil/oshrc':12: warning: Coercing undefined value to 0 in arithmetic context
*** Error has no source location info ***
fatal: Expected array in index expression, got 0
```

By the way, are you aware that brace sequence expression expansion (e.g. `{1..3}`) and braces in `for` loops instead of `do`/`done` (undocumented but unfortunately used) aren't supported by OSH?

**Comment by andychu** [comment] 2019-05-07 16:05
Thanks, fixing issue #287 should fix this.  Right now the arithmetic evaluator is too specific to integers.

Yes I know about the brace expansion issue.  The brace-expansion file has 12 failing tests, most of which are related to that:

http://www.oilshell.org/release/0.6.pre18/test/spec.wwz/

But I'm basically doing things on demand in order to fill out 

https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

Surprisingly, none of those scripts depend on integer expansion.  I guess because it doesn't accept variables, so is only of use interactively.  But if you're relying on that interactively, I'll take that as a bug :)

I've seen the braces in for loop issue (although I haven't seen it documented), but again no programs seem to rely on that.  Or maybe I found just one that relied on it.

**Comment by Crestwave** [comment] 2019-05-08 00:37
> But I'm basically doing things on demand in order to fill out
> 
> https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH
> 
> Surprisingly, none of those scripts depend on integer expansion. I guess because it doesn't accept variables, so is only of use interactively. But if you're relying on that interactively, I'll take that as a bug :)

Yes, I often use it interactively. It's also a decent amount faster, I think, so I'd use it if looping over a large fixed set of numbers in scripts. It also allows you to do things in one go instead of looping for each number, which can also dramatically increase speed.

> I've seen the braces in for loop issue (although I haven't seen it documented), but again no programs seem to rely on that. Or maybe I found just one that relied on it.

Yes, it's undocumented, but dylanaraps (his `fff` is on the list, and [Neofetch](https://github.com/dylanaraps/neofetch) is very popular) uses it in most of his programs, even using `for ((;;)) {` for infinite loops.

**Comment by andychu** [comment] 2019-05-08 06:12
OK I filed #303 for brace expansion.

I see the `{` issue... it's probably worth fixing to see if neofetch runs, since it's bash 3.2 and 8000 lines... would be nice to run it.

```
$ osh -n neofetch
Line 4261 of 'neofetch'
          for ((i=0;i<${#sw_vers[@]};i+=2)) {
                                            ^
Invalid word after for expression
```

**Comment by Crestwave** [comment] 2019-05-08 06:13
> I see the `{` issue... it's probably worth fixing to see if neofetch runs, since it's bash 3.2 and 8000 lines... would be nice to run it.
> 
> ```
> $ osh -n neofetch
> Line 4261 of 'neofetch'
>           for ((i=0;i<${#sw_vers[@]};i+=2)) {
>                                             ^
> Invalid word after for expression
> ```

IIRC it uses `printf -v`, which OSH doesn't have yet

**Comment by andychu** [comment] 2019-05-15 20:19
@Crestwave I just commited `printf` support, with `-v`:

https://github.com/oilshell/oil/commit/5ec3366dc87cea4c599bee13c8511f122c0c8ff6

Feedback is apprecaited!

**Comment by Crestwave** [comment] 2019-05-17 08:00
> @Crestwave I just commited `printf` support, with `-v`:
> 
> [5ec3366](https://github.com/oilshell/oil/commit/5ec3366dc87cea4c599bee13c8511f122c0c8ff6)
> 
> Feedback is apprecaited!

Sorry for the late reply; my internet was down for a few days. It doesn't seem to support assigning to array elements, e.g., `printf -v "arr[1]" foo`.

**Comment by andychu** [comment] 2019-05-19 04:04
Yes good point!

I mentioned this "cell sublanguage" that `printf -v` respects along with `unset` and `${!x}` on my blog.  OSH doesn't implement yet.  As usual, it will be bumped up if an important program can't run without it.

(BTW my motivation for implementing `printf` was mostly speed, since autoconf aliases `echo` to `printf %s` for portability reasons.  Unfortunately that didn't speed up Python's configure script under OSH :-( )

But adding a spec test did reveal that OSH wasn't validating the variable name!  I just committed a check for that.

**Comment by andychu** [comment] 2019-07-13 06:01
Revisiting the to issue raised in the very first message, I think OSH is doing what I intend now, although it's different than bash.  Let me know if what you think.


```
$ bin/osh -c '(( arr[0] ))'
  (( arr[0] ))
     ^~~
[ -c flag ]:1: fatal: Undefined value in arithmetic context (0 if shopt -u strict-arith)
```

Then unsetting strict arith:

```
$ bin/osh -c 'shopt -u strict-arith; (( arr[0] ))'
  shopt -u strict-arith; (( arr[0] ))
                            ^~~
[ -c flag ]:1: warning: Undefined value in arithmetic context (0 if shopt -u strict-arith)
  shopt -u strict-arith; (( arr[0] ))
                         ^~
[ -c flag ]:1: fatal: Expected array in index expression, got 0
```

The warnings are a bit noisy but the basic idea is right.

**Comment by andychu** [comment] 2019-07-13 06:35
Oh I guess you can argue that since `undefined[5]=0`, then `(( undefined[5] = 0 ))` should work similarly.  Let me think...

**Comment by andychu** [comment] 2019-07-17 19:28
Released with https://www.oilshell.org/release/0.7.pre1/

I did a big overhaul of associative arrays and array semantics, and unified them with the command mode syntax.

`(( undefined[5] = 42 ))` now works like the command version.  `(( arr[0] ))` fails by design.  If some real shell script relies on some other behavior, I could be convinced.

**Closed by andychu** 2019-07-17 19:28 UTC
Labels: osh-language, pending-release
