### ISSUE TITLE
Ctrl-C in command substitution exits parent shell

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#467] opened 2019-08-18 15:14 UTC
Repro steps:

```
(bash) ~ $ osh --rcfile /dev/null
osh$ `sleep 1`
^C
(bash) ~ $
```

Expected behavior: osh sends interrupt to command substitution, but continues reading input and behaving as an interactive shell (same as bash and dash)

Actual behavior: osh exits completely!

This looks like it was introduced by https://github.com/oilshell/oil/commit/119123831356b97b6557e3dd186cb28ec69c7f4a, which enables 'Ctrl-C' during command substitions. osh should distinguish between interrupting the substitution and interrupting the parent shell.

**Comment by andychu** [comment] 2019-09-18 01:07
OK I reproduced this... my memory of how it works is already fuzzy :-/

But thank you for the report and testing!

**Comment by andychu** [comment] 2022-01-05 22:22
Hm looks like this fell through the cracks, should take another look at it

**Comment by andychu** [comment] 2022-01-30 18:52
Fixed in 0.9.7: https://www.oilshell.org/blog/2022/01/notes-themes.html

As mentioned in the blog post, I probably subconsciously put this off because we didn't have a good test harness!

**Closed by andychu** 2022-01-30 18:52 UTC
Labels: high-priority, pending-release, signal-handling
