### ISSUE TITLE
wait isn't interruptable

### ISSUE THREAD

**Issue by terinjokes** [oilshell/oil#858] opened 2020-11-05 09:14 UTC
I've noticed that wait isn't interruptable like it is in bash, which cased some issues with scripts relying on background sleep and trap behavior.

---

This is a trivial reproduction case trimmed from a project with lots of similar scripts.

```shell
action() {
	echo "from signal" | ts
}

status() {
	# do some background status report
	date
}

trap "action" USR1

echo $$ | ts
while true; do
        status
	sleep 10 &
	wait $!
done
```

--- 

When running in bash, sending USR1 to the process will immediately run the trap handler.

```
$ bash ./test.sh
Nov 05 01:07:01 7362
Thu 05 Nov 2020 01:07:01 AM PST
Thu 05 Nov 2020 01:07:11 AM PST
Nov 05 01:07:13 from signal
Thu 05 Nov 2020 01:07:13 AM PST
Nov 05 01:07:14 from signal
Thu 05 Nov 2020 01:07:14 AM PST
Nov 05 01:07:15 from signal
Thu 05 Nov 2020 01:07:15 AM PST
Thu 05 Nov 2020 01:07:25 AM PST
^C
```

```
$ kill -USR1 7362 && date
Thu 05 Nov 2020 01:07:13 AM PST
$ kill -USR1 7362 && date
Thu 05 Nov 2020 01:07:14 AM PST
$ kill -USR1 7362 && date
Thu 05 Nov 2020 01:07:15 AM PST
```

---

Running the same script in osh requires us to wait for the full 10 second sleep before the handler is executed.

```
$ osh ./test.sh
Nov 05 01:09:31 8770
Thu 05 Nov 2020 01:09:31 AM PST
[%1] Started PID 8774
Thu 05 Nov 2020 01:09:41 AM PST
[%2] Started PID 8857
Nov 05 01:09:51 from signal
Thu 05 Nov 2020 01:09:51 AM PST
[%3] Started PID 8933
Nov 05 01:10:01 from signal
Thu 05 Nov 2020 01:10:01 AM PST
[%4] Started PID 9001
Nov 05 01:10:11 from signal
Nov 05 01:10:11 from signal
Thu 05 Nov 2020 01:10:11 AM PST
[%5] Started PID 9094
Thu 05 Nov 2020 01:10:21 AM PST
[%6] Started PID 9178
^C
```

```
$ kill -USR1 8770 && date
Thu 05 Nov 2020 01:09:44 AM PST
$ kill -USR1 8770 && date
Thu 05 Nov 2020 01:09:55 AM PST
$ kill -USR1 8770 && date
Thu 05 Nov 2020 01:10:03 AM PST
$ kill -USR1 8770 && date
Thu 05 Nov 2020 01:10:05 AM PST
```

**Comment by andychu** [comment] 2020-11-05 18:51
Thanks for the report!  I reproduced this  bug.

I think the bug is that signal handlers run in the main interpreter loop, and `wait $pid` runs in its own loop until the process stops.

Originally I thought this would be better fixed in the C++ translation, because signals are a bit different there, but it's possible it is an algorithmic problem.   I'll look into it, thanks!

**Comment by andychu** [comment] 2021-01-21 19:44
I just fixed this -- thanks for this great bug report!

It looks like bash/zsh/mksh all have a special  flag to make the `wait` builtin interruptable.  (dash doesn't have it, so it has the same bug!)

The fix will be out with the next release.

-----

Sort of related: I'm looking for feedback on Oil's enhanced shell tracing:

http://www.oilshell.org/preview/doc/xtrace.html


https://old.reddit.com/r/oilshell/comments/l0sshn/tracing_execution_in_oil_set_x_xtrace/

**Comment by andychu** [comment] 2021-01-25 18:27
Fixed https://www.oilshell.org/release/0.8.7/

**Closed by andychu** 2021-01-25 18:27 UTC
Labels: correctness, divergence, pending-release

**Comment by terinjokes** [comment] 2021-01-25 18:40
Oh wow, `xtrace` looks awesome for debugging.

**Comment by andychu** [comment] 2021-01-25 22:35
Yup I just used it to debug some really poorly formatted code in #881 -- it was a big improvement.  It's still early and up for discussion.  More ideas on #891 !

It's out with 0.8.7 so keep it in mind when you need to debug :)
