### ISSUE TITLE
detection methods: if "script is being sourced" (bash deviation, fatal error)

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1696] opened 2023-08-13 21:03 UTC
[quotes from follow-up posts below]:
> wanted to not execute more than some init stuff when being sourced (function calls controlled by sourcing script), while defaulting to specific functions/actions according to how the called script (symlink) is named.

Got several errors experimenting with the following method to detect if a script is being run directly or sourced
`(return 0 2>/dev/null) && sourced=1 || sourced=0`

(This method as posted at https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
is basicly expected to work in all shells where `return 0` fails with exit code >0 if called on top level (e.g. bash), while avoiding the specific bash variables and possibly pitfalls of `[ "$0" = "$BASH_SOURCE" ]`. The method is also related to "exit instead of returning, if executed directly": `return 2>/dev/null || exit`)

However, in osh the error(s) seem fatal. Examples:
```
osh-0.17.0$ (return 0)
  (return 0)
   ^~~~~~
[ interactive ]:1: fatal: Invalid control flow 'return' in pipeline / subshell / background
```

EDIT: split-off osh error with "forkwait { true }", and ysh error message related to parsing "if forkwait"

----
Does ysh maybe support a better/direct/obvious/readable method to determine if code being sourced?
Would it be worthwhile?

----

Solution:

- [ ]  let `return` exit with status >0 if called in top level (bash behavior), instead of throwing a fatal error. (Or let it auto-fallback to do an exit like other shells???)

> Concerning an integrated ysh feature, might it make sense to?
- possibly let `runproc`  *not* run the specified proc, _if being sourced_? (with options `--even-if-sourced` and `--only-if-sourced`?) (-> See #1011 ???)

> [Concerning a compatible detection method working in ysh and ordinary (posix) shell (basic osh)...]
-  provide special var `$_this_name` (or better named: `$_script_name`) in osh and ysh.
  This is for backwards compatibility with ordinary shells, for where scripts may provide a static fallback `${_script_name:-fixedname.sh}` to work with a static default script name. (-> see #1701)

**Comment by bar-g** [comment] 2023-08-13 21:09
```
ysh$ (return 0)
  (return 0)
   ^~~~~~
[ interactive ]:1: fatal: Invalid control flow 'return' in pipeline / subshell / background
```
I would rather have expected some expression error in ysh.

**Comment by bar-g** [comment] 2023-08-13 21:51
I guess, at the end some osh+ysh portable way may be using `$(return 0)`? To avoid the subshell vs. expression syntax conflict?

**Comment by andychu** [comment] 2023-08-14 15:56
e.g. at the end of this doc we have a "module"

https://www.oilshell.org/release/latest/doc/ysh-tour.html#appendix-example-of-an-oil-module

I think we can provide an idiomatic way to run only if it's "main" -- does that solve the problem you're tackling, or it something else?

**Comment by bar-g** [comment] 2023-08-15 10:40
Basicly I wanted to not execute more than init stuff when being sourced (function calls controlled by sourcing script), while defaulting to specific functions/actions according to how the script is called.

Concerning integrated ysh features, might it make sense to 

- [ ]  let `runproc`  *not* run the specified proc, if being sourced?

Concerning other/old compatible shell (basic osh) implementation, that `if $(return 0)` test just looked like the worst cryptic and least specific from the alternative stackoverflow answers to me, unfortunately still not really portable, e.g. in ash and dash IIRC. However, works well with bash and the fatal osh error deviates from it (as well as from other shells that exit upon `return` on top level).

Hm, your `test "$(basename $0)" = thisfile.sh;` would require a fixed and known file name in other/old shells (unlike the stackoverflow answers), but looks simple and fully portable, is that right?

Then maybe

- [ ]  provide `$_this_file` in osh and ysh

to allow using it in backwards compatible scripts if available, with a static fallback just for other shells?

**Comment by bar-g** [comment] 2023-08-15 11:26
BTW: `$_this_dir/file`, couldn'd simply `$_script_dir/file` provide some more direct meaning? "This" seems to me as conveying too much of something current or dynamic, or only "this" thing from many things.

**Comment by bar-g** [comment] 2023-08-16 11:23
Oh, well. The name of the variable(s) might really rather be something like
`$_exec_dir/$_exec_file` vs.  `$_script_dir/$_script_file`. 
To make it much clearer that, and how, they differ when using the `source`.

**Comment by bar-g** [comment] 2023-08-16 11:49
Sorry, got confused by orig. intention of #587, `$_this_dir` does always point to the dir of "_this_script".
Having `$_this_script` and possibly `$_exec_script` may still be clearer.

**Comment by andychu** [comment] 2023-08-23 00:07
BTW `$_this_dir` is supposed to point to the script being interpreted (sourced or executed), which is in general not the same as the script you ran

**Comment by bar-g** [comment] 2023-08-23 18:06
Oh, I meant to edit my confused posed after my follow-up message, but found it still unedited only now, sorry.

Of course `$_this_dir` is fine. And counting`$0` to the positional parameters, there's no need to divert it into `$_exec_file`. I updated my post and the description above now.

**Comment by bar-g** [comment] 2023-08-24 12:07
Since it turned out `$0` can't be relied upon, `$_exec_script` seems still needed, nevertheless: #1708

**Comment by andychu** [comment] 2023-08-30 01:46
OK I think this is a dupe of #1011

**Closed by andychu** 2023-08-30 01:46 UTC

**Comment by bar-g** [comment] 2023-08-31 08:12
Thought this issue was for the bash compat behavior of `return 0`.

**Comment by bar-g** [comment] 2023-08-31 09:14
I could change the title but not re-open.
