### ISSUE TITLE
Can't use unquoted (balanced) brackets in associative array subscripts

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#771] opened 2020-06-12 01:04 UTC
Not sure if this is worth supporting; it's used by `nosj` but I don't think Dylan would necessarily be opposed to quoting it since it fails if the brackets aren't balanced.

```bash
$ declare -A arr
$ arr[[]]=foo
$ echo "${arr[[]]}"
foo
```

```sh
osh$ declare -A arr
osh$ arr[[]]=foo
  arr[[]]=foo
      ^
[ array LValue in (source.Interactive) ]:2: Token can't be used in prefix position
osh$ echo "${arr[[]]}"
  echo "${arr[[]]}"
              ^
[ interactive ]:3: Token can't be used in prefix position
```

**Comment by andychu** [comment] 2020-06-12 04:05
Yeah if the `[]` is a string, then it should be quoted in OSH, documented here:

https://www.oilshell.org/release/0.8.pre5/doc/known-differences.html#strings-vs-bare-words-in-array-indices

(I have a patch for the bash version of mal Lisp that does this too... )

**Comment by andychu** [comment] 2020-06-12 19:42
Closing since this is working as intended, let me know if you disagree!

**Closed by andychu** 2020-06-12 19:42 UTC
