### ISSUE TITLE
Error applying ad-hoc signature, when installed with homebrew

### ISSUE THREAD

**Issue by wickles** [oilshell/oil#1725] opened 2023-09-13 19:30 UTC
```
❯ brew install oil
==> Downloading https://ghcr.io/v2/homebrew/core/oil/manifests/0.18.0
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/6c2add264f3bbf0575363dee4eac8d746bead283d24b959fe5d395c0f63be14d--oil-0.18.0.bottle_manifest.json
==> Fetching oil
==> Downloading https://ghcr.io/v2/homebrew/core/oil/blobs/sha256:bc276b9884f67c70b7cdf53f8c5c4442dd9cc249946c26d2b8674b
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/3dc72261d5b3e7d5aa5fd400cf5c9f8c2fd0c231388d73ca686165b5a76e964a--oil--0.18.0.arm64_ventura.bottle.tar.gz
==> Pouring oil--0.18.0.arm64_ventura.bottle.tar.gz
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/oil/0.18.0/bin/oil.ovm:
/opt/homebrew/Cellar/oil/0.18.0/bin/oil.ovm: replacing existing signature
/opt/homebrew/Cellar/oil/0.18.0/bin/oil.ovm: main executable failed strict validation

🍺  /opt/homebrew/Cellar/oil/0.18.0: 8 files, 4.7MB
==> Running `brew cleanup oil`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

Not sure if this is a homebrew issue since it [passes CI](https://github.com/Homebrew/homebrew-core/actions/runs/6173868324/job/16757262964)

**Comment by andychu** [comment] 2023-09-14 05:15
Hmm is this a new problem?   Are you the maintainer of the homebrew package?

One thing I can think of is that `oil.ovm` is an ELF file with a .zip file appended to it, and that sometimes causes problems

But it's been like that for 5 years, so it shouldn't be happening now

---

We are moving toward the `oils-for-unix` C++ tarball - https://www.oilshell.org/release/0.18.0/

It is very complete for OSH, but not for YSH yet

**Comment by wickles** [comment] 2023-09-14 16:04
@andychu I am not the maintainer. This is not a new issue though, it has happened for me with every release I have tried. However it does not seem to interfere with the installation or running the shell after installation.

**Comment by PossiblyAShrub** [comment] 2023-09-14 23:05
It's definitely related to the zip file appended to the end. According to [apple's docs](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG309), the error is caused by:
> - Your Mach-O executable does not conform to modern Mach-O layout rules.
> - You may be using a third party development product that hasn't been brought up to date, or post-processed your file in unsupported ways

Appending arbitrary bytes at the end of the executable probably falls under "post-processed your file in unsupported ways". But this is only an issue being raised by `codesign`. Darwin doesn't care about the extra data when loading the mach-o binary for execution.

<details>
  <summary>Simple reproduction displaying this behaviour.</summary>

  ```
  $ cat main.c
  #include <stdio.h>
  
  int main() {
    puts("hello");
    return 0;
  }
  $ clang main.c -o program
  $ ./program
  hello
  $ codesign -vv program
  program: valid on disk
  program: satisfies its Designated Requirement
  
  $ echo "Hello" > data
  $ zip data.zip data
  updating: data (stored 0%)
  
  $ cat program data.zip >bundle
  $ chmod +x bundle
  $ ./bundle
  hello
  $ codesign -vv bundle
  bundle: main executable failed strict validation
  ```
</details>

I can confirm that this issue is not present on the native build.

**Comment by andychu** [comment] 2023-09-15 00:24
Thanks Aidan!  That makes sense

Yeah this technique caused problems  with `strip` too, so that's why we're not using it with the C++ binary

Instead we just embed C++ data structures, so it's a normal binary

---

Our plan is to gradually remove the Python tarball in favor of the C++ one, so there's no real point to fixing this now

We also have to remind everyone to name it `oils-for-unix`, not `oilshell` and so forth

https://github.com/oilshell/oil/wiki/Oil-Deployments

**Closed by andychu** 2023-09-15 00:24 UTC

**Comment by lishaduck** [comment] 2024-06-03 14:37
Should be fixed for good now, @wickles!
I ran into this upgrading to Oils 0.22.0, so I went ahead and PRed to Homebrew, which now uses the C++ tarball.
Run `brew uninstall oil && brew install oils-for-unix` to migrate 🥳
